# 00. PyTorch Fundamentals

Resource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/




In [181]:
from psutil import win_service_get #获取 Windows 系统上的服务信息
!nvidia-smi

Fri May 30 15:40:22 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 572.40                 Driver Version: 572.40         CUDA Version: 12.8     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 4070 ...  WDDM  |   00000000:01:00.0 Off |                  N/A |
| N/A   44C    P3             16W /   67W |       0MiB /   8188MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

**Google colab** (Jupyter Notebook  .ipynb)

右上角connect先, runtime-change runtime type - GPU<br><br>
在code cell - python 中:

* !nvidia-smi   监控 NVIDIA GPU 的状态和性
* Shift+enter 运行代码
* Ctrl MM to turn code cell into text cell
<br>

在text cell - markdown 中：
* ##通常用于创建 Markdown 标题(二级标题)
* < br>是换行标签
* < hr>是水平分割线 <hr>
* < p>创建段落，段落间有较大间距< /p>  
<p>这是一个段落</p>
* 两个`之间 可以作为代码样式
* ...

In [1]:
import torch                       #导入pyTorch库
import pandas as pd                #导入Pandas库
import numpy as np                 #导入Numpy库
import matplotlib.pyplot as plt    #导入Matplotlib库

print(torch.__version__)           #打印pyTorch的版本号  cu124是CUDA 12.4

2.7.0+cu128


## Introduction to Tensors 张量

### Creating tensors

In [8]:
# scalar 标量张量
scalar = torch.tensor(7)
scalar


tensor(7)

In [10]:
scalar.ndim #查看维度，标量是0维

0

In [ ]:
scalar.item() #将张量转换为 Python int

7

In [ ]:
# Vector 向量
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim #闭合方括号]的数量，1维

1

In [ ]:
vector.shape #形状 数的数量

torch.Size([2])

In [ ]:
# MATRIX 矩阵
MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim #维度，两个],2维

2

In [ ]:
MATRIX[0]

tensor([7, 8])

In [ ]:
MATRIX[1]

tensor([ 9, 10])

In [ ]:
MATRIX.shape   #[]的数量, 数的数量

torch.Size([2, 2])

In [ ]:
# TENSOR 张量
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [ ]:
TENSOR[0][1]

tensor([3, 6, 9])

In [ ]:
TENSOR.ndim  #3个],但张量可以是任何维度

3

In [ ]:
TENSOR.shape  #ndim-1开始     [[]]的数量, []的数量，数字的数量

torch.Size([1, 3, 3])

In [ ]:
ComplexTENSOR = torch.tensor([[[[1,2,3,5],
                                [3,6,9,4],
                                [2,4,5,3],
                                [4,4,4,2],
                                [1,1,1,2]],
                               [[1,2,3,5],
                                [3,6,9,4],
                                [2,4,5,3],
                                [4,4,4,2],
                                [1,1,1,2]]]])
ComplexTENSOR

tensor([[[[1, 2, 3, 5],
          [3, 6, 9, 4],
          [2, 4, 5, 3],
          [4, 4, 4, 2],
          [1, 1, 1, 2]],

         [[1, 2, 3, 5],
          [3, 6, 9, 4],
          [2, 4, 5, 3],
          [4, 4, 4, 2],
          [1, 1, 1, 2]]]])

In [ ]:
ComplexTENSOR[0]

tensor([[[1, 2, 3, 5],
         [3, 6, 9, 4],
         [2, 4, 5, 3],
         [4, 4, 4, 2],
         [1, 1, 1, 2]],

        [[1, 2, 3, 5],
         [3, 6, 9, 4],
         [2, 4, 5, 3],
         [4, 4, 4, 2],
         [1, 1, 1, 2]]])

In [ ]:
ComplexTENSOR.ndim  #4个]

4

In [ ]:
ComplexTENSOR.shape # [[[]]]数量1 [[]]数量2 []数量5  数字数量4

torch.Size([1, 2, 5, 4])

scalar, vector 变量名小写 <br>
MATRIX, TENSOR 变量名大写

### Random tensors 随机张量

随机张量很重要，因为许多神经网络的学习方式是他们从充满随机数的张量开始,
然后调整这些随机数以更好地表示数据。<br>
`Start with random numbers -> look at data -> update random numbers
-> look at data -> update random numbers`




In [ ]:
# create a random tensor of size/shape ([3,4])  ndim=1+1  3个[]  4个数           [[]]1个
random_tensor = torch.rand(3,4) #torch.rand(size=(3,4))同种意思
random_tensor

tensor([[0.7731, 0.1257, 0.2882, 0.6766],
        [0.1866, 0.2867, 0.4451, 0.8294],
        [0.6499, 0.0762, 0.6184, 0.9674]])

In [ ]:
random_tensor.ndim   #]数量

2

In [ ]:
#create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3,224,224))  #颜色通道（RGB)，高度，宽度
random_image_size_tensor.shape, random_image_size_tensor.ndim  #size是2 1 0， ndim=2+1

(torch.Size([3, 224, 224]), 3)

### Zeros and ones

In [ ]:
#create a tensor of all zeros
zeros = torch.zeros(size=(3,4))       #3[]  4         1[[]]
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
zeros * random_tensor  #mask 掩码-用同一个size的tensor 忽略无效数据

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
#create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype  #default data type 默认的都是torch.float32  浮点数

torch.float32

### create a range of tensors and tensors-like

In [ ]:
# Use torch.arange()  一个范围的tensor
one_to_ten = torch.arange(start=1,end=11,step=1)  #起点(默认0），终于(不包括),步长(默认1)
one_to_ten    #start, end, step可省略 1,11,1

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
zero_to_nine = torch.arange(10) #0-9
zero_to_nine

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# creating tensors-like 相同shape/size的tensor
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
ones = torch.ones_like(one_to_ten)         # 全1
fives = torch.full_like(one_to_ten, 5)   # 全5
fives

tensor([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

### Tensor datatypes
1. Tensors not right datatypes
2. Tensors not right shape
3. Tensors not on the right device

In [7]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=None,  #what datatype is the tensor (e.g. float32 单精度 or float16 半精度)
                               device=None, #what device is your tensor on: cpu, cuda
                               requires_grad=False)  #whether or not to track 梯度 gradient 求导
float_32_tensor

tensor([3., 6., 9.])

In [6]:
float_32_tensor.dtype  #即使明说了是None,也是float32 默认

torch.float32

In [8]:
float_16_tensor = float_32_tensor.type(torch.float16) #跟f32一样的3，6，9，但类型变了
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [9]:
float_32_tensor * float_16_tensor

tensor([ 9., 36., 81.])

In [10]:
int_32_tensor = torch.tensor([3,6,9],dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [11]:
float_32_tensor * int_32_tensor    #貌似类型不匹配不会出错，但以后可能会有错

tensor([ 9., 36., 81.])

### Tensor datatypes
1. Tensors not right datatypes  - `tensor.dtype`
2. Tensors not right shape  - `tensor.shape`
3. Tensors not on the right device - `tensor.device`

In [16]:
# create a tensor
some_tensor = torch.rand((3,4))  #  3[]  4      1[[]]
some_tensor

tensor([[0.4050, 0.3458, 0.8678, 0.6637],
        [0.0740, 0.9203, 0.2590, 0.6012],
        [0.3108, 0.3027, 0.1994, 0.8277]])

In [17]:
# Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device of tensor: {some_tensor.device}") #默认是cpu

tensor([[0.4050, 0.3458, 0.8678, 0.6637],
        [0.0740, 0.9203, 0.2590, 0.6012],
        [0.3108, 0.3027, 0.1994, 0.8277]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device of tensor: cpu


### Manipulating Tensors (tensor operations)

Tensor operations include:
* addition
* subtraction
* multiplication (element-wise) 元素对元素
* division
* matrix multiplication


In [2]:
# create a tensor
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [40]:
tensor*10

tensor([10., 20., 30.])

In [41]:
tensor

tensor([1., 2., 3.])

In [42]:
#减10
tensor - 10

tensor([-9., -8., -7.])

In [43]:
# try out pytorch in-built functions
torch.mul(tensor,10)

tensor([10., 20., 30.])

In [44]:
torch.add(tensor,10)

tensor([11., 12., 13.])

### Matrix multiplication

2种方式在神经网络和深度学习：
1. element-wise mult
2. matrix mult (dot product)

There are two rules that performing matrix multiplcation needs to satisfy:
1. The **inner dimensions** must match:          @也是matrixmult
* `(3,2) @ (3,2)` wont work
* `(2,3) @ (3,2)` will work
* `(3,2) @ (2,3)` will work

2.The resulting matrix has the shape of the **outer dimensions**
* `(2,3) @ (3,2)` -> `(2,2)`
* `(3,2) @ (2,3)` -> `(3,3)`

In [3]:
torch.matmul(torch.rand(3,2),torch.rand(2,3))

tensor([[0.0870, 0.0715, 0.2417],
        [0.2116, 0.1884, 0.3470],
        [0.1621, 0.1466, 0.2285]])

In [4]:
torch.matmul(torch.rand(2,3),torch.rand(3,2))

tensor([[0.8306, 1.0496],
        [0.9694, 1.0601]])

In [5]:
# Element-wise
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")              #size(3) 和 size(3)

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [6]:
# matrix multiplication
# 1,2,3 dot 1,2,3
torch.matmul(tensor,tensor)

tensor(14)

In [12]:
%%time
#测量整个代码单元格
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: total: 0 ns
Wall time: 1.52 ms


In [172]:
# 二维张量（3行2列）
tensor_2d = torch.tensor([[1, 2], [3, 4], [5, 6]])
print(len(tensor_2d))  # 输出: 3（第一维的大小，即行数）  []个数

# 三维张量（批量大小为2，每个包含3行4列）
tensor_3d = torch.randn(2, 3, 4)  # 形状: [2, 3, 4]      2[[]] 3[] 4       1[[[]]]
print(len(tensor_3d))  # 输出: 2（第一维的大小，即批量大小）[[]]
print(tensor_3d) # torch.randn 是生成mean=0,标准差=1,的标准状态分布的随机数

3
2
tensor([[[ 1.0661, -0.0306, -1.1709, -0.6065],
         [-0.8554, -0.9551,  0.4564,  0.6468],
         [-0.7069,  1.5065,  1.3334, -0.5071]],

        [[ 2.8094, -0.1971,  0.7987,  0.5144],
         [-0.5750,  0.5259,  0.3850,  1.4188],
         [-0.2461,  0.1371,  0.3935, -0.2432]]])


In [14]:
%%time
torch.matmul(tensor,tensor)  #完全更快

CPU times: total: 0 ns
Wall time: 192 μs


tensor(14)

In [16]:
A = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])  # 形状: [2, 3]
B = torch.tensor([[7, 8],
                  [9, 10],
                  [11,12]])  # 形状: [3, 2]
'''
1,2,3 dot 7,9,11
1,2,3 dot 8,10,12
4,5,6 dot 7,9,11
4,5,6 dot 8,10,12
'''

# 矩阵乘法
C = torch.matmul(A, B)
print(C)

tensor([[ 58,  64],
        [139, 154]])


In [ ]:
# 创建两个二维矩阵
A = torch.tensor([[1, 2],
                  [3, 4]])  # 形状: [2, 2]
B = torch.tensor([[5, 6],
                  [7, 8]])  # 形状: [2, 2]

# 矩阵乘法
C = torch.matmul(A, B)

'''
1,2 dot 5,7 = 19
1,2 dot 6,8 = 22
3,4 dot 5,7 = 15+28=43
3,4 dot 6,8 = 18+32=50
'''
print(C)
# 输出:
# tensor([[19, 22],
#         [43, 50]])

In [17]:
A = torch.tensor([[1, 2],
                  [3, 4]])  # 形状: [2, 2]
v = torch.tensor([5, 6])            # 形状: [2]（一维向量）

# 矩阵乘向量
w = A @ v
'''
1,2 dot 5,6 = 5+12=17
3,4 dot 5,6 = 15+24=39
'''
print(w)
# 输出:
# tensor([17, 39])   #shape [2]

tensor([17, 39])


### one of the most common errors in deep learning : shape errors

In [18]:
# shapes for matrix multiplication
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])   #shape 3,2

tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])  #shape 3,2

# torch.mm(tensor_A, tensor_B)   #mm也是matmul

#但是这里无法矩阵乘法， 3by2 x 3by2

### 使用transpose 转置/维度交换 来改变一个张量的形状

In [23]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [24]:
tensor_B.T,tensor_B.T.shape  #转置后的B

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [26]:
output = torch.matmul(tensor_A,tensor_B.T)
output, output.shape

(tensor([[ 27,  30,  33],
         [ 61,  68,  75],
         [ 95, 106, 117]]),
 torch.Size([3, 3]))

In [19]:
#                 tensor 交换的两个维度的索引（从 0 开始）
# torch.transpose(input, dim0, dim1)

                                        #index    0  1         #ndim 2
x = torch.tensor([[1, 2, 3], [4, 5, 6]])  # 形状: [2, 3]
y = torch.transpose(x, 0, 1)  # 交换维度0和1
# 等价于 y = x.transpose(0, 1) 或 y = x.T（仅适用于二维张量，两个]]）

print(f"原始形状: {x.shape}")  # 输出: torch.Size([2, 3])
print(f"转置后形状: {y.shape}")  # 输出: torch.Size([3, 2])

原始形状: torch.Size([2, 3])
转置后形状: torch.Size([3, 2])


In [20]:
x = torch.randn(2, 3, 4)  # 形状: [2, 3, 4]

# 交换维度1和2    index1,2
y = torch.transpose(x, 1, 2)  # 形状变为 [2, 4, 3]

print(f"原始形状: {x.shape}")  # 输出: torch.Size([2, 3, 4])
print(f"转置后形状: {y.shape}")  # 输出: torch.Size([2, 4, 3])

原始形状: torch.Size([2, 3, 4])
转置后形状: torch.Size([2, 4, 3])


### Tensor Aggregation 张量聚合
Find the min, max, mean 平均值, sum, etc.

In [30]:
# Create a tensor
x = torch.arange(0,100,10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [28]:
# Find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [29]:
# Find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [33]:
# Find the mean   这里int64即long会报错求平均值，转为其他dtype
torch.mean(x.type(torch.float32)),  x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [36]:
# Find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

## Finding the positional min and max 最小/大值所在的index

In [42]:
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [43]:
#最小值index - argmin
x.argmin()

tensor(0)

In [44]:
x[0]

tensor(1)

In [46]:
#最小值index - argmax
x.argmax()

tensor(9)

In [48]:
x[9]

tensor(91)

## Reshaping 重塑,stacking 堆叠
## squeezing 压缩 and unsqueezing 扩展 tensors
* reshaping - 改变张量的形状
* view - 返回张量的视图
* stacking - 合并多个张量  竖直vstack 水平hstack
* squeeze - 去除张量的所有1维
* unsqueeze - 给张量加上1维
* permute - 返回一个维度排列被置换的输入的视图

In [116]:
# create a tensor
x = torch.arange(1.,10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [53]:
# reshape, 加上1维, 多了1个[]在外面， 元素量要匹配 reshape 1,7 不行 1*7=7
#                                                   2,9 不行 2*9=18

#[1,9]    1[] 9    1[[]]

x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [54]:
x_reshaped = x.reshape(9,1)       # 9[] 1        1[[]]
x_reshaped, x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [122]:
# change the view视图, 视图和原张量共享一块内存，跟reshape很像
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [144]:
'''

[[1., 2., 3., 4., 5., 6., 7., 8., 9.]]
shape[1,9]

: 全选  dim=0         []内
0     dim=1      index0  1.
                    [1.]

'''

print(z[:, 0])  #tensor([1.])   , shape [1]
#改z也会改x，把[]内的数改成5，x也会跟着改
z[:, 0] = 5
z, x

tensor([1.])


(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [126]:
# x shape [9]
# stack tensors on top of each other 张量堆叠               4在dim0
x_stacked = torch.stack([x,x,x,x], dim=0)  #堆叠4个x  36个数  [4,9]
x_stacked, x_stacked.shape

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 torch.Size([4, 9]))

In [59]:
x_stacked = torch.stack([x,x,x,x], dim=1)  #重新排列后堆叠 [9,4] 4在dim1
x_stacked, x_stacked.shape

(tensor([[5., 5., 5., 5.],
         [2., 2., 2., 2.],
         [3., 3., 3., 3.],
         [4., 4., 4., 4.],
         [5., 5., 5., 5.],
         [6., 6., 6., 6.],
         [7., 7., 7., 7.],
         [8., 8., 8., 8.],
         [9., 9., 9., 9.]]),
 torch.Size([9, 4]))

In [ ]:
'''

原始形状          [9]
dim = 0         [4,9]   4在index0
      1         [9,4]   4在index1


如果是shape    [2,3]
dim=0：在最前面插入新维度，结果形状为 [4, 2, 3]。  4在index 0 = dim0
dim=1：在中间插入新维度，结果形状为 [2, 4, 3]。
dim=2：在最后插入新维度，结果形状为 [2, 3, 4]。
'''

In [61]:
x = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])  #shape    [2,3]

# 在第0维（新维度）上堆叠4个x
x_stacked = torch.stack([x, x, x, x], dim=0) #[4,2,3]

print("堆叠后的张量:")
print(x_stacked, x_stacked.shape)
# 输出:

堆叠后的张量:
tensor([[[1, 2, 3],
         [4, 5, 6]],

        [[1, 2, 3],
         [4, 5, 6]],

        [[1, 2, 3],
         [4, 5, 6]],

        [[1, 2, 3],
         [4, 5, 6]]]) torch.Size([4, 2, 3])


In [62]:
x_stacked = torch.stack([x, x, x, x], dim=1)
print("堆叠后的张量:")
print(x_stacked, x_stacked.shape)

堆叠后的张量:
tensor([[[1, 2, 3],
         [1, 2, 3],
         [1, 2, 3],
         [1, 2, 3]],

        [[4, 5, 6],
         [4, 5, 6],
         [4, 5, 6],
         [4, 5, 6]]]) torch.Size([2, 4, 3])


In [63]:
x_stacked = torch.stack([x, x, x, x], dim=2)
print("堆叠后的张量:")
print(x_stacked, x_stacked.shape)

堆叠后的张量:
tensor([[[1, 1, 1, 1],
         [2, 2, 2, 2],
         [3, 3, 3, 3]],

        [[4, 4, 4, 4],
         [5, 5, 5, 5],
         [6, 6, 6, 6]]]) torch.Size([2, 3, 4])


### Hstack, Vstack 水平/竖直堆叠

In [66]:
a = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])  # 形状: [2, 3]
b = torch.tensor([[7, 8, 9],
                  [10, 11, 12]])  # 形状: [2, 3]

hstacked = torch.hstack([a, b])   # 等价于 torch.cat([a, b], dim=1)
hstacked, hstacked.shape         #[2,3+3] 水平堆，横着的数字多

(tensor([[ 1,  2,  3,  7,  8,  9],
         [ 4,  5,  6, 10, 11, 12]]),
 torch.Size([2, 6]))

In [67]:
vstacked = torch.vstack([a, b]) #等价于torch.cat([a, b], dim=0)
vstacked, vstacked.shape       #[2+2,3] 竖直堆，纵向的[]多

(tensor([[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([4, 3]))

与 stack 的对比 <br>
hstack/vstack：在现有维度上拼接，不增加新维度。<br>
torch.stack()：在新维度上堆叠，增加维度数

### Squeeze 压缩

In [68]:
# torch.squeeze() - 去除张量的所有1维
x = torch.randn(1,3,1,224,224)  #形状[1, 3, 1, 224, 224]
x_squeezed = torch.squeeze(x)
x_squeezed.shape    #torch.Size([3, 224, 224])

torch.Size([3, 224, 224])

In [69]:
# 创建一个形状为 [1, 5] 的张量
y = torch.randn(1, 5)  # 形状: [1, 5]

# 仅移除第0维（大小为1）
y_squeezed_0 = torch.squeeze(y, dim=0)  # 形状: [5]

# 尝试移除第1维（大小为5不是1，不移除）
y_squeezed_1 = torch.squeeze(y, dim=1)  # 形状: [1, 5]（不变）

print("移除第0维:", y_squeezed_0.shape)  # 输出: torch.Size([5])
print("移除第1维:", y_squeezed_1.shape)  # 输出: torch.Size([1, 5])

移除第0维: torch.Size([5])
移除第1维: torch.Size([1, 5])


In [74]:
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

#remove extra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}"
      f"\nNew shape: {x_squeezed.shape}")


Previous tensor: tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])
Previous shape: torch.Size([9, 1])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


### Unsqueeze 扩展

In [71]:
# 创建一个形状为 [3, 4] 的张量
x = torch.randn(3, 4)  # 形状: [3, 4]

# 在第0维前插入一个维度   dim0放1
x_unsqueezed_0 = torch.unsqueeze(x, dim=0)  # 形状: [1, 3, 4]

# 在第1维前插入一个维度
x_unsqueezed_1 = torch.unsqueeze(x, dim=1)  # 形状: [3, 1, 4]

# 在最后一维后插入一个维度（等价于 dim=2）
x_unsqueezed_2 = torch.unsqueeze(x, dim=-1)  # 形状: [3, 4, 1]
print("原始形状:", x.shape)  # 输出: torch.Size([3, 4])
print("插入第0维:", x_unsqueezed_0.shape)  # 输出: torch.Size([1, 3, 4])
print("插入第1维:", x_unsqueezed_1.shape)  # 输出: torch.Size([3, 1, 4])
print("插入最后一维:", x_unsqueezed_2.shape)  # 输出: torch.Size([3, 4, 1])

原始形状: torch.Size([3, 4])
插入第0维: torch.Size([1, 3, 4])
插入第1维: torch.Size([3, 1, 4])
插入最后一维: torch.Size([3, 4, 1])


In [80]:
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

#加上1维
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [78]:
x_reshaped.squeeze()

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

### Permute 重新排序维度, 也是一种视图，共享内存
示例 1：二维矩阵转置（等价于 transpose）

In [87]:
 # 创建一个2x3的矩阵
x = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])  # 形状: [2, 3]

# 使用 permute 实现转置（交换维度0和1）  [3,2]
x_permuted = torch.permute(x, (1, 0))  # 等价于 x.transpose(0, 1)

print("原始形状:", x.shape)  # 输出: torch.Size([2, 3])
print("转置后形状:", x_permuted.shape)  # 输出: torch.Size([3, 2])

原始形状: torch.Size([2, 3])
转置后形状: torch.Size([3, 2])


示例 2：三维张量维度重排

In [89]:
# 创建一个形状为 [2, 3, 4] 的三维张量
x = torch.randn(2, 3, 4)  # 形状: [2, 3, 4]

# 重新排列维度为                    [4, 2, 3]
x_permuted = torch.permute(x, (2, 0, 1))
print("原始形状:", x.shape)  # 输出: torch.Size([2, 3, 4])
print("重排后形状:", x_permuted.shape)  # 输出: torch.Size([4, 2, 3])

原始形状: torch.Size([2, 3, 4])
重排后形状: torch.Size([4, 2, 3])


In [95]:
#图像数据
x_original = torch.rand(size = (224,224,3))   #高度，宽度，颜色通道

#Permute the original tensor to 重排维度
x_permuted = x_original.permute(2, 0, 1)

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [96]:
                              #torch.Size([224, 224, 3])
x_original[0,0,0]         #等价于x_original[0][0][0]

tensor(0.1691)

In [97]:
x_original[0,0,0]  = 72818
x_original[0,0,0], x_permuted[0,0,0]    #也被改了，因为也是view

(tensor(72818.), tensor(72818.))

## indexing (selecting data from tensors)
Indexing with PyTorch is similar to indexing with Numpy

In [146]:
#create a tensor
import torch
x = torch.arange(1,10).reshape(1,3,3)  #9个值 1*3*3
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [150]:
# Lets index on our new tensor
x[0], x[0].shape

(tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]),
 torch.Size([3, 3]))

In [103]:
# Lets index on the middle bracket (dim=1)  [1, 3, 3]的3行
x[0][0]

tensor([1, 2, 3])

In [108]:
# Lets index on the most inner bracket (last dimension)
x[0][2][2]

tensor(9)

In [111]:
# You can also ":" to select "all" of a target dimension
'''
第0维  dim0

[1,3,3]
第0维 1   [[]]
第1维 3    []
第2维 3

                ([[[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]]])
x[:, 0]
:   第0维中所有元素       [[]]               ---从这里开始算上[]
0   第1维中index 0的     index0的[1,2,3]
                合体后结果:  [[1,2,3]]
'''
x[:,0],x[:,0].shape

(tensor([[1, 2, 3]]), torch.Size([1, 3]))

In [148]:
#获取所有0维和1维的值，但只获取2维的index1
'''
        [[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]

          shape [1, 3, 3]
        :  [[]]            ---从这里开始算上[]
        :   []内            -- 也要
        1   index1的数   2,5,8

    结果    [[2,5,8]]

x[:,:,数]情况下 --  每个:都要算上[]
'''
x[:,:,1], x.shape

(tensor([[2, 5, 8]]), torch.Size([1, 3, 3]))

In [149]:
# 获取dim0的所有值，但只获取1维和2维的index1
'''
        [[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]

          shape [1, 3, 3]

          dim0   [[]]                --不算
          dim1   index1 [4,5,6]内的   --开始算上[]
          dim2  index1  5

          [5]

x[:,数,数]，以这第一个数的维度开始算上[]
'''
x[:,1,1]        #tensor([5])

tensor([5])

In [151]:
x[0,1,1] #这个没有:就很简单  纯数字 tensor(5)

tensor(5)

In [152]:
# 获取dim0和dim1的index0,和dim2的所有值
'''
        [[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]

          shape [1, 3, 3]
          dim0 [[1,2,3],
                [4,5,6],
                [7,8,9]]
         dim1   [1,2,3]     --开始算上[]
         dim2   所有数字1,2,3

         [1,2,3]

x[数,数,:]，以第二个数开始算上方括号
从内开始合体
'''
x[0,0,:]

tensor([1, 2, 3])

In [155]:
# index on x to return 9 #单个数字简单
print(x[0,2,2])

'''
        [[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]

        shape [1, 3, 3]

        dim0   [[1,2,3],
                [4,5,6],
                [7,8,9]]
        dim1  :   []         --开始算上[]
        dim2  2  index2的数3,6,9


[数,:,数] - 从:才开始算上方括号
[3,6,9]
'''
#index on x to return 3,6,9  #多个数字不简单，一列的
print(x[0,:,2])


tensor(9)
tensor([3, 6, 9])


In [156]:
'''
法二
        [[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]

        shape [1, 3, 3]

        dim0  :  [[]]内
        dim1  :   []内
        dim2  2  index2的数
        [[3,6,9]]
'''
print(x[:,:,2])  #

tensor([[3, 6, 9]])


## Pytorch tensors & Numpy

Numpy is a popular scientific python numerical computation library.
And because of this, pytorch has functionality to interact it.

* numpy 转 pytorch tensor -> `torch.from_numpy(ndarray)`
* pytorch tensor 转 numpy -> `torch.Tensor.numpy()`

In [157]:
# numpy array to tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)  #转成了张量，转过来是float64
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [158]:
array.dtype  #默认是64位浮点数

dtype('float64')

In [159]:
torch.arange(1.0, 8.0).dtype    #默认是32位浮点数

torch.float32

In [161]:
tensor = torch.from_numpy(array).type(torch.float32)
tensor.dtype

torch.float32

In [168]:
# 改array的值，张量没有变化
array = array + 1
array,tensor

(array([2., 3., 4., 5., 6., 7., 8.]), tensor([1., 1., 1., 1., 1., 1., 1.]))

In [169]:
# Tensor to numpy array
tensor = torch.ones(7)
numpy_array = tensor.numpy()
tensor, numpy_array  #默认32位

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [170]:
# 改tensor， numpy_array不会被改变
tensor = tensor + 1
tensor, numpy_array

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

### Reproducity 可重现性 - 试图消除随机性
神经网络学习从随机数开始-tensor operations-update随机数让他们不断更好地呈现-重复重复...

为了减少随机性，有个**random seed**的概念，随机种子作用是调整随机性 flavor

pseudorandomness 伪随机 p不发音

In [176]:
import torch

#create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)  #不太可能相等

tensor([[0.1150, 0.5938, 0.4360, 0.7190],
        [0.9644, 0.3459, 0.2730, 0.5255],
        [0.6108, 0.6793, 0.1615, 0.4528]])
tensor([[0.3452, 0.0106, 0.7481, 0.9619],
        [0.4960, 0.7634, 0.7174, 0.0300],
        [0.0459, 0.8586, 0.3811, 0.6978]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [178]:
# 让我们做些随机但可重现的张量
import torch

# 设置随机种子
RANDOM_SEED = 42 #默认是42

torch.manual_seed(RANDOM_SEED)  #每次随机前都要设置下
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and pytorch objects on GPUs and 计算地更快

GPUs = 更快的数字计算  因为CUDA, NVIDIA,和pytorch背后计算

选项
1. google Colab
2. 自己的GPU
3. cloud computing - GCP, AWS, Azure

### check for GPU access with pytorch

In [185]:
# check for GPU access with pytorch
import torch
torch.cuda.is_available()

True

In [186]:
# setup device agnostic code 设备无关性
# 自动选择可用的计算设备（GPU 或 CPU）
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [187]:
# count number of devices
torch.cuda.device_count()

1

## 3. Putting tensors and models on the GPU

The reason we want to put on GPU 因为他快

In [189]:
# create a tensor (default on CPU)
tensor = torch.tensor([1,2,3],device="cpu")

#不在gpu上
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [190]:
# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### 4.Moving tensors back to CPU

In [193]:
# if tensor is on GPU, 不能转换成numpy
# tensor_on_gpu.numpy() 会报错！

In [195]:
# 解决方法 - 设置一个在cpu上的
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [196]:
tensor_on_gpu #还是在gpu上面

tensor([1, 2, 3], device='cuda:0')

## Exercise & Extracurriculars
作业: https://github.com/mrdbourke/pytorch-deep-learning/blob/main/extras/exercises/00_pytorch_fundamentals_exercises.ipynb <br>
答案：https://github.com/mrdbourke/pytorch-deep-learning/tree/main/extras/solutions


THE END
<hr>