# 00. PyTorch Fundamentals

Resource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/




In [2]:
from psutil import win_service_get
!nvidia-smi

Wed May 28 16:51:05 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 572.40                 Driver Version: 572.40         CUDA Version: 12.8     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 4070 ...  WDDM  |   00000000:01:00.0 Off |                  N/A |
| N/A   45C    P3             16W /   68W |       0MiB /   8188MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

**Google colab** (Jupyter Notebook  .ipynb)

右上角connect先, runtime-change runtime type - GPU<br><br>
在code cell - python 中:

* !nvidia-smi   监控 NVIDIA GPU 的状态和性
* Shift+enter 运行代码
* Ctrl MM to turn code cell into text cell

<br>

在text cell - markdown 中：
* ##通常用于创建 Markdown 标题(二级标题)
* < br>是换行标签
* < hr>是水平分割线 <hr>
* < p>创建段落，段落间有较大间距< /p>  
<p>这是一个段落</p>
* 两个`之间 可以作为代码样式
* ...

In [2]:
import torch                       #导入pyTorch库
import pandas as pd                #导入Pandas库
import numpy as np                 #导入Numpy库
import matplotlib.pyplot as plt    #导入Matplotlib库

print(torch.__version__)           #打印pyTorch的版本号  cu124是CUDA 12.4

2.7.0+cu128


## Introduction to Tensors 张量

### Creating tensors

In [8]:
# scalar 标量张量
scalar = torch.tensor(7)
scalar


tensor(7)

In [10]:
scalar.ndim #查看维度，标量是0维

0

In [ ]:
scalar.item() #将张量转换为 Python int

7

In [ ]:
# Vector 向量
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim #闭合方括号的数量，1维

1

In [ ]:
vector.shape #形状 数的数量

torch.Size([2])

In [ ]:
# MATRIX 矩阵
MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim #维度，两个],2维

2

In [ ]:
MATRIX[0]

tensor([7, 8])

In [ ]:
MATRIX[1]

tensor([ 9, 10])

In [ ]:
MATRIX.shape   #[]的数量 数的数量

torch.Size([2, 2])

In [ ]:
# TENSOR 张量
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [ ]:
TENSOR[0][1]

tensor([3, 6, 9])

In [ ]:
TENSOR.ndim  #3个],但张量可以是任何维度

3

In [ ]:
TENSOR.shape  #ndim-1开始   [[]]的数量, []的数量，数字的数量

torch.Size([1, 3, 3])

In [ ]:
ComplexTENSOR = torch.tensor([[[[1,2,3,5],
                                [3,6,9,4],
                                [2,4,5,3],
                                [4,4,4,2],
                                [1,1,1,2]],
                               [[1,2,3,5],
                                [3,6,9,4],
                                [2,4,5,3],
                                [4,4,4,2],
                                [1,1,1,2]]]])
ComplexTENSOR

tensor([[[[1, 2, 3, 5],
          [3, 6, 9, 4],
          [2, 4, 5, 3],
          [4, 4, 4, 2],
          [1, 1, 1, 2]],

         [[1, 2, 3, 5],
          [3, 6, 9, 4],
          [2, 4, 5, 3],
          [4, 4, 4, 2],
          [1, 1, 1, 2]]]])

In [ ]:
ComplexTENSOR[0]

tensor([[[1, 2, 3, 5],
         [3, 6, 9, 4],
         [2, 4, 5, 3],
         [4, 4, 4, 2],
         [1, 1, 1, 2]],

        [[1, 2, 3, 5],
         [3, 6, 9, 4],
         [2, 4, 5, 3],
         [4, 4, 4, 2],
         [1, 1, 1, 2]]])

In [ ]:
ComplexTENSOR.ndim  #4个]

4

In [ ]:
ComplexTENSOR.shape #[[[[]]]]数量1 [[[]]]数量1 [[]]数量2 []数量5  数字数量4

torch.Size([1, 2, 5, 4])

scalar, vector 变量名小写 <br>
MATRIX, TENSOR 变量名大写

### Random tensors 随机张量

随机张量很重要，因为许多神经网络的学习方式是他们从充满随机数的张量开始,
然后调整这些随机数以更好地表示数据。<br>
`Start with random numbers -> look at data -> update random numbers
-> look at data -> update random numbers`




In [ ]:
# create a random tensor of size/shape ([3,4])  ndim=1+1  3个[]  4个数
random_tensor = torch.rand(3,4) #torch.rand(size=(3,4))同种意思
random_tensor

tensor([[0.7731, 0.1257, 0.2882, 0.6766],
        [0.1866, 0.2867, 0.4451, 0.8294],
        [0.6499, 0.0762, 0.6184, 0.9674]])

In [ ]:
random_tensor.ndim   #]数量

2

In [ ]:
#create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3,224,224))  #颜色通道（RGB)，高度，宽度
random_image_size_tensor.shape, random_image_size_tensor.ndim  #size是2 1 0， ndim=2+1

(torch.Size([3, 224, 224]), 3)

### Zeros and ones

In [ ]:
#create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
zeros * random_tensor  #mask 掩码-用同一个size的tensor 忽略无效数据

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
#create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype  #default data type 默认的都是torch.float32  浮点数

torch.float32

### create a range of tensors and tensors-like

In [ ]:
# Use torch.arange()  一个范围的tensor
one_to_ten = torch.arange(start=1,end=11,step=1)  #起点(默认0），终于(不包括),步长(默认1)
one_to_ten    #start, end, step可省略 1,11,1

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
zero_to_nine = torch.arange(10) #0-9
zero_to_nine

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# creating tensors-like 相同shape/size的tensor
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
ones = torch.ones_like(one_to_ten)         # 全1
fives = torch.full_like(one_to_ten, 5)   # 全5
fives

tensor([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

### Tensor datatypes
1. Tensors not right datatypes
2. Tensors not right shape
3. Tensors not on the right device

In [7]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=None,  #what datatype is the tensor (e.g. float32 单精度 or float16 半精度)
                               device=None, #what device is your tensor on: cpu, cuda
                               requires_grad=False)  #whether or not to track 梯度
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
%%sql


In [6]:
float_32_tensor.dtype  #即使明说了是None,也是float32 默认

torch.float32

In [8]:
float_16_tensor = float_32_tensor.type(torch.float16) #16 位浮点数
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [9]:
float_32_tensor * float_16_tensor

tensor([ 9., 36., 81.])

In [10]:
int_32_tensor = torch.tensor([3,6,9],dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [11]:
float_32_tensor * int_32_tensor    #貌似不会出错，但以后可能会有错

tensor([ 9., 36., 81.])

### Tensor datatypes
1. Tensors not right datatypes  - `tensor.dtype`
2. Tensors not right shape  - `tensor.shape`
3. Tensors not on the right device - `tensor.device`

In [16]:
# create a tensor
some_tensor = torch.rand((3,4))
some_tensor

tensor([[0.4050, 0.3458, 0.8678, 0.6637],
        [0.0740, 0.9203, 0.2590, 0.6012],
        [0.3108, 0.3027, 0.1994, 0.8277]])

In [17]:
# Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device of tensor: {some_tensor.device}") #默认是cpu

tensor([[0.4050, 0.3458, 0.8678, 0.6637],
        [0.0740, 0.9203, 0.2590, 0.6012],
        [0.3108, 0.3027, 0.1994, 0.8277]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device of tensor: cpu


### Manipulating Tensors (tensor operations)

Tensor operations include:
* addition
* subtraction
* multiplication (element-wise)
* division
* matrix multiplication
j

In [19]:
# create a tensor
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [40]:
tensor*10

tensor([10., 20., 30.])

In [41]:
tensor

tensor([1., 2., 3.])

In [42]:
#减10
tensor - 10

tensor([-9., -8., -7.])

In [43]:
# try out pytorch in-built functions
torch.mul(tensor,10)

tensor([10., 20., 30.])

In [44]:
torch.add(tensor,10)

tensor([11., 12., 13.])

### Matrix multiplication

2种方式在神经网络和深度学习：
1. element-wise
2. matrix  (dot product)

There are two rules that performing matrix multiplcation needs to satisfy:
1. The **inner dimensions** must match:          @也是matrixmult
* `(3,2) @ (3,2)` wont work
* `(2,3) @ (3,2)` will work
* `(3,2) @ (2,3)` will work

2.The resulting matrix has the shape of the **outer dimensions**
* `(2,3) @ (3,2)` -> `(2,2)`
* `(3,2) @ (2,3)` -> `(3,3)`

In [51]:
torch.matmul(torch.rand(3,2),torch.rand(2,3))

tensor([[0.5811, 0.7590, 0.8167],
        [0.1429, 0.0947, 0.2366],
        [0.6055, 0.7699, 0.8591]])

In [52]:
torch.matmul(torch.rand(2,3),torch.rand(3,2))

tensor([[0.6241, 1.3365],
        [0.4189, 0.7340]])

In [46]:
# Element-wise
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1., 2., 3.]) * tensor([1., 2., 3.])
Equals: tensor([1., 4., 9.])


In [47]:
# matrix multiplication   #1*1+2*2+3*3=14
torch.matmul(tensor,tensor)

tensor(14.)

In [48]:
%%time   #测量整个代码单元格
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
print(value)

tensor(14.)
CPU times: total: 0 ns
Wall time: 1.51 ms


In [49]:
%%time
torch.matmul(tensor,tensor)  #完全更快

CPU times: total: 0 ns
Wall time: 185 μs


tensor(14.)

### one of the most common errors in deep learning : shape errors

In [53]:
# shapes for matrix multiplication
tensor_A = torch.tensor([[1,2],
                        [3,4],
                        [5,6]])

tensor_B = torch.tensor([[7,10],
                        [8,11],
                        [9,12]])

# torch.mm(tensor_A, tensor_B)   #mm也是matmul

#但是这里无法矩阵乘法， 3by2 x 3by2

使用transpose 转置交换 来改变一个张量的dimension

In [ ]:
tensor_B.T, tensor